### ISSUE TITLE
Error on https://fast-namerena.pages.dev/

### ISSUE THREAD

**Issue by CuteMurasame** [shenjackyuanjie/fast-namerena#1]
F12 Console:

![image](https://github.com/user-attachments/assets/5d282a74-35e3-4584-a46b-314af8c03b3d)

F12 Network:

![image](https://github.com/user-attachments/assets/6039350d-0b0d-47c0-a7d8-c98bedf21b93)

I can load <https://static.cloudflareinsights.com/beacon.min.js>, and here <https://fast-namerena.pages.dev/lzma_worker-min.js> looks same as <https://fast-namerena.pages.dev/>

**Comment by CuteMurasame** [comment]
Browser ver:

![image](https://github.com/user-attachments/assets/66391aa9-97e3-49a1-a1a8-0035450c0b46)

**Comment by shenjackyuanjie** [comment]
一眼顶针：鉴定为：我不知道
稍等我待会看一眼

**Comment by shenjackyuanjie** [comment]
我这里本地没问题欸

**Comment by shenjackyuanjie** [comment]
@nr0728 你确定现在还会稳定存在这个问题吗

**Comment by shenjackyuanjie** [comment]
没回我就关了（

**Comment by CuteMurasame** [comment]
> @nr0728 你确定现在还会稳定存在这个问题吗

抱歉一段时间没上github，现在没问题了
